# Generated by Django 5.1.7 on 2026-03-28 19:03

import credentials.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.CharField(blank=True, help_text='e.g. https://device.local — used to build links in tools', max_length=500)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('api_token', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('verify_ssl', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HTTPS Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SNMPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=4)),
                ('community', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('v3_username', models.CharField(blank=True, max_length=100)),
                ('auth_protocol', models.CharField(blank=True, choices=[('', 'None'), ('MD5', 'MD5'), ('SHA', 'SHA-1'), ('SHA-224', 'SHA-224'), ('SHA-256', 'SHA-256'), ('SHA-384', 'SHA-384'), ('SHA-512', 'SHA-512')], max_length=10)),
                ('auth_password', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('priv_protocol', models.CharField(blank=True, choices=[('', 'None'), ('DES', 'DES'), ('AES', 'AES-128'), ('AES-192', 'AES-192'), ('AES-256', 'AES-256')], max_length=10)),
                ('priv_password', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SNMP Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSHProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=22)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('key', 'Private Key')], default='password', max_length=10)),
                ('password', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('private_key', credentials.fields.EncryptedTextField(blank=True, default='')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSH Profile',
                'ordering': ['name'],
            },
        ),
    ]
