# Generated by Django 5.1.7 on 2026-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('', '— Unknown —'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('load_balancer', 'Load Balancer'), ('vpn', 'VPN Concentrator'), ('ups', 'UPS / PDU'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned'), ('in_stock', 'In Stock')], default='active', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('https_profiles', models.ManyToManyField(blank=True, related_name='network_devices', to='credentials.httpsprofile')),
                ('snmp_profiles', models.ManyToManyField(blank=True, related_name='network_devices', to='credentials.snmpprofile')),
                ('ssh_profiles', models.ManyToManyField(blank=True, related_name='network_devices', to='credentials.sshprofile')),
            ],
            options={
                'verbose_name': 'Network Device',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('server_type', models.CharField(blank=True, choices=[('', '— Unknown —'), ('physical', 'Physical'), ('vm', 'Virtual Machine'), ('container', 'Container Host'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned'), ('in_stock', 'In Stock')], default='active', max_length=20)),
                ('os_type', models.CharField(blank=True, choices=[('', '— Unknown —'), ('linux', 'Linux'), ('windows', 'Windows'), ('esxi', 'VMware ESXi'), ('other', 'Other')], max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('https_profiles', models.ManyToManyField(blank=True, related_name='servers', to='credentials.httpsprofile')),
                ('ssh_profiles', models.ManyToManyField(blank=True, related_name='servers', to='credentials.sshprofile')),
            ],
            options={
                'verbose_name': 'Server',
                'ordering': ['name'],
            },
        ),
    ]
