# Generated by Django 5.1.7 on 2026-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='os_version',
            field=models.CharField(blank=True, help_text='OS/software version from SNMP poll', max_length=200),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_sysname',
            field=models.CharField(blank=True, help_text="sysName from SNMP poll (device's own hostname)", max_length=200),
        ),
    ]
